# coding=utf-8
DIRECTION_UNKNOWN = 0
DIRECTION_LONG = 1
DIRECTION_SHORT = 2
DIRECTION_NET = 3
OFFSET_UNKNOWN = 0
OFFSET_OPEN = 1
OFFSET_CLOSE = 2
OFFSET_CLOSETODAY = 3
OFFSET_CLOSEYESTERDAY = 4
STATUS_UNKNOWN = 0
STATUS_NOTTRADED = 1
STATUS_PARTTRADED = 2
STATUS_ALLTRADED = 3
STATUS_CANCELLED = 4
PRODUCT_UNKNOWN = 0
PRODUCT_EQUITY = 1
PRODUCT_FUTURES = 2
PRICETYPE_UNKONWN = 0
PRICETYPE_LIMITPRICE = 1
PRICETYPE_MARKETPRICE = 2
NOTIFICATION_UNKNOWN = 0
NOTIFICATION_TRADEWILLBEGIN = 1
NOTIFICATION_GOTCONTRACTS = 2

#_CLIENT_ID = "bfCtaTemplate"
#_MT = [("clientid",_CLIENT_ID)]
# 默认空值
EMPTY_STRING = ''
EMPTY_UNICODE = u''
EMPTY_INT = 0
EMPTY_FLOAT = 0.0
TR_Direction=[u'未知',u'买入',u'卖出',u'Net']
TR_Offset=[u'未知',u'开仓',u'平仓',u'平今',u'平昨']
class EMPTY_CLASS:pass